#!/usr/bin/expect --

set timeout 600
## set PASS to the first argument
set PASS [lrange $argv 0 0]

spawn sudo /sbin/iptables -L
expect ":" { send "$PASS\r" }
expect "anywhere"

spawn sudo cp /home/ben/ALL/webserver/servername.conf /etc/apache2/conf.d/servername.conf
expect ":" { send "$PASS\r" }

spawn sudo /usr/sbin/apache2ctl graceful
expect ":" { send "$PASS\r" }

spawn /usr/sbin/apache2ctl configtest
expect "Syntax OK"

spawn curl -I http://103.1.184.46
expect "200 OK"
