#! /bin/sh

PASS=$1

echo $PASS | sudo -S cp /home/carlo/ALL/webserver/certs/glamormommy.com.crt /etc/ssl/certs/glamormommy.com.crt
echo $PASS | sudo -S cp /home/carlo/ALL/webserver/certs/glamormommy.com.crt /etc/ssl/private/glamormommy.com.key
