#! /bin/sh

PASS=$1

mkdir -p /home/carlo/public_html
mkdir -p /home/carlo/public_html/glamor_mommy
mkdir -p /home/carlo/public_html/glamor_mommy_demo
mkdir -p /home/carlo/public_html/glamor_mommy_staging

echo $PASS | sudo -S chmod -R a+rX /home/carlo/public_html
echo $PASS | sudo -S chmod a+rx /home/carlo
echo $PASS | sudo -S cp /home/carlo/ALL/webserver/virtual_hosts/* /etc/apache2/sites-available/.

echo $PASS | sudo -S a2ensite marilyn.23inhouse.com
echo $PASS | sudo -S a2ensite securecellardoor.com
echo $PASS | sudo -S a2ensite glamormommy.com
bash --login -c "echo $PASS | sudo -S /etc/init.d/apache2 reload"
