#! /bin/bash

## set the password
PASS=$1


#
# http://articles.slicehost.com/2010/4/30/ubuntu-lucid-setup-part-1
#

## Add a new user
scp ~/.ssh/id_rsa.pub root@192.168.1.6:/home/root/id_rsa.pub
ssh -t root@192.168.1.6 "sudo adduser carlo && sudo /usr/sbin/usermod -a -G admin carlo && cd /home/carlo/ && sudo mkdir -p /home/carlo/.ssh && sudo mv ~/id_rsa.pub /home/carlo/.ssh/authorized_keys && sudo chown -R carlo:carlo .ssh && sudo chmod 700 .ssh && sudo chmod 600 .ssh/authorized_keys && sudo mkdir -p /home/carlo/ALL/setup && sudo chown -R carlo:carlo /home/carlo/ALL && sudo aptitude install expect"

## copy the scripts over
scp ./ALL/setup/* carlo@192.168.1.6:/home/carlo/ALL/setup/.

## SSH config
ssh -t carlo@192.168.1.6 "/home/carlo/ALL/setup/ssh_config $PASS"

## iptables
ssh -t carlo@192.168.1.6 "/home/carlo/ALL/setup/iptables $PASS" # PLEASE CHECK THESE DETAILS.

#
# http://articles.slicehost.com/2010/4/30/ubuntu-lucid-setup-part-2
#

## OS check
ssh -p 30000 -t carlo@192.168.1.6 "/home/carlo/ALL/setup/os_check $PASS"

# Update
ssh -p 30000 -t carlo@192.168.1.6 "/home/carlo/ALL/setup/update $PASS"


