#! /bin/bash

## set the password
PASS=$1

## copy the scripts over
ssh -p 30000 -t carlo@192.168.1.6 "mkdir -p /home/carlo/ALL/install"
scp -rP 30000 ./ALL/install/* carlo@192.168.1.6:/home/carlo/ALL/install/.

#
# http://www.mammothvps.com.au/kb/troubleshooting/mpanel-memory-graph
#

ssh -p 30000 -t carlo@192.168.1.6 "/home/carlo/ALL/install/mPanel-memory-graph $PASS"


ssh -p 30000 -t carlo@192.168.1.6 "/home/carlo/ALL/install/packages $PASS"

#
# https://github.com/sstephenson/rcarlov
#

ssh -p 30000 -t carlo@192.168.1.6 "/home/carlo/ALL/install/ruby $PASS"


ssh -p 30000 -t carlo@192.168.1.6 "/home/carlo/ALL/install/gems $PASS"


#
# http://articles.slicehost.com/2009/5/6/ubuntu-hardy-postgresql-installation
#

ssh -p 30000 -t carlo@192.168.1.6 "/home/carlo/ALL/install/postgresql-conf $PASS"


#
# https://github.com/jdpace/PDFKit/wiki/Installing-WKHTMLTOPDF
#

ssh -p 30000 -t carlo@192.168.1.6 "/home/carlo/ALL/install/wkhtmltopdf $PASS" # 32BIT OSES


#
# http://www.bookofzeus.com/articles/how-to-install-memcached-in-ubuntu/
# http://www.exclusivetutorials.com/memcached-server-installation/
#

ssh -p 30000 -t carlo@192.168.1.6 "/home/carlo/ALL/install/memcached $PASS" # THIS ONE DOESN'T WORK - do it manually
