#! /bin/bash

## set the password
PASS=$1

## copy the scripts over
ssh -p 30000 -t ben@103.1.184.46 "mkdir -p /home/ben/ALL/install"
scp -rP 30000 ./ALL/install/* ben@103.1.184.46:/home/ben/ALL/install/.

#
# http://www.mammothvps.com.au/kb/troubleshooting/mpanel-memory-graph
#

ssh -p 30000 -t ben@103.1.184.46 "/home/ben/ALL/install/mPanel-memory-graph $PASS"


ssh -p 30000 -t ben@103.1.184.46 "/home/ben/ALL/install/packages $PASS"

#
# https://github.com/sstephenson/rbenv
#

ssh -p 30000 -t ben@103.1.184.46 "/home/ben/ALL/install/ruby $PASS"


ssh -p 30000 -t ben@103.1.184.46 "/home/ben/ALL/install/gems $PASS"


#
# http://articles.slicehost.com/2009/5/6/ubuntu-hardy-postgresql-installation
#

ssh -p 30000 -t ben@103.1.184.46 "/home/ben/ALL/install/postgresql-conf $PASS"
