#!/usr/bin/expect --

set timeout 600
## set PASS to the first argument
set PASS [lrange $argv 0 0]

spawn createuser -PE marilyn
expect ":" { send "monroe!\r" }
expect ":" { send "monroe!\r" }
expect "(y/n)" { send "n\r" }
expect "(y/n)" { send "y\r" }
expect "(y/n)" { send "n\r" }

spawn psql
expect "postgres" { send "SELECT * FROM pg_user;\r" }
expect "usename" { send "\q\r"}