#! /bin/sh

PASS=$1

createdb -O marilyn -E UTF8 glamor_mommy_test
createdb -O marilyn -E UTF8 glamor_mommy_staging
createdb -O marilyn -E UTF8 glamor_mommy_demo
createdb -O marilyn -E UTF8 glamor_mommy
