#! /bin/sh

PASS=$1

## install rbenv
git clone git://github.com/sstephenson/rbenv.git .rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> .bash_profile
echo 'eval "$(rbenv init -)"' >> .bash_profile

git clone git://github.com/sstephenson/ruby-build.git
export PREFIX="$HOME/.rbenv/"
cd /home/ben/ruby-build
/home/ben/ruby-build/install.sh
cd ..
rm -rf /home/ben/ruby-build

export PATH="$HOME/.rbenv/bin:$PATH"
rbenv install 1.9.2-p290 && rbenv rehash
rbenv global 1.9.2-p290
