#! /bin/sh

PASS=$1

## install rcarlov
git clone git://github.com/sstephenson/rcarlov.git .rcarlov
echo '. "$HOME/.bashrc"' >> .bash_profile
echo '' >> .bash_profile
echo 'export PATH="$HOME/.rcarlov/bin:$PATH"' >> .bash_profile
echo 'eval "$(rcarlov init -)"' >> .bash_profile

git clone git://github.com/sstephenson/ruby-build.git
export PREFIX="$HOME/.rcarlov/"
cd /home/carlo/ruby-build
/home/carlo/ruby-build/install.sh
cd ..
rm -rf /home/carlo/ruby-build

export PATH="$HOME/.rcarlov/bin:$PATH"
rcarlov install 1.9.2-p290 && rcarlov rehash
rcarlov global 1.9.2-p290
